
- name: "install dependencies for nginx"
  apt:
    name: ["python-passlib","python3-apt","wget","git","build-essential","libpcre3","libpcre3-dev","libssl-dev","libtool","autoconf","apache2-dev","libxml2-dev","libcurl4-openssl-dev","automake","pkgconf","zlib1g-dev","liblua5.1-0","flex","bison","curl","doxygen","libyajl-dev","yajl-tools","libgeoip-dev","libtool","dh-autoreconf","libcurl4-gnutls-dev","libxml2","libpcre++-dev","libxml2-dev"]
    state: present

- name: "unarchive"  
  unarchive:
    src: "https://www.openssl.org/source/openssl-1.1.1c.tar.gz"     
    dest: /usr/src/
    remote_src: yes
    validate_certs: false

- name: "Shell openssl"
  shell: "./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib"
  args:
    chdir: /usr/src/openssl-1.1.1c/

- name: "Openssl"
  shell:  openssl version
  register: opens


- name: "Make openssl"
  make:
    chdir: /usr/src/openssl-1.1.1c/
  make:
    chdir: /usr/src/openssl-1.1.1c/
    target: test
  make:
    chdir: /usr/src/openssl-1.1.1c/
    target: install
  when: opens.stdout.find("1.1.1c") != -1

- name: "Config openssl"
  shell: echo "/usr/local/ssl/lib" > /etc/ld.so.conf.d/
  shell: ldconfig -v 
  shell: echo "PATH=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/ssl/bin\"" > /etc/environment
  args:
    executable: /bin/bash
  shell: source /etc/environment
